version: '3'

services:

  meals-service:
    build: ./meals
    volumes:
      - type: bind
        source: ./meals  #host directory
        target: /meals # container directory
    environment:
      FLASK_DEBUG: "true"
    ports:
      - "5001:5001"  # host:container

  diet-service:
    build: ./diets
    volumes:
      - type: bind
        source: ./diets #host directory
        target: /diets # container directory
    environment:
      FLASK_DEBUG: "true"
    ports:
      - "5002:5002"  # host:container

  reverse:
    build: ./reverse
    ports:
      - "80:80"
    depends_on:
      - meals-service
      - diet-service

#  mongo:
#    image: mongo
#    ports:
#      - "27017:27017" # In daniels example mapping is without quotes
#    volumes:
#      - mongo_data:/data/db
#
#volumes:
#  mongo_data: