FROM python:alpine3.17
WORKDIR ./app
RUN pip install requests
RUN pip install flask
RUN pip install flask_restful

COPY dietsService.py .
ENV FLASK_APP=main.py
ENV FLASK_RUN_PORT=5002
CMD ["flask", "run", "--host=0.0.0.0"]