version: '3'

services:

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017 # In daniels example mapping is without quotes
    volumes:
      - mongo_data:/data/db


  diets-service:
    build: ./diets
    restart: always
    volumes:
      - type: bind
        source: ./diets #host directory
        target: /diets # container directory
    environment:
      FLASK_DEBUG: "true"
    ports:
      - "5002:5002"  # host:container
    expose:
      - 5002
    depends_on:
      - mongo

  meals-service:
    build: ./meals
    restart: always
    volumes:
      - type: bind
        source: ./meals  #host directory
        target: /meals # container directory
    environment:
      FLASK_DEBUG: "true"
    ports:
      - "5001:5001"  # host:container
    depends_on:
      - diets-service


  reverse:
    build: ./reverse
    ports:
      - "80:80"
    depends_on:
      - meals-service
      - diets-service

volumes:
  mongo_data:
