version: '3'

services:

  meals-service:
    build: ./meals
    volumes:
      - type: bind
        source: ./meals  #host directory
        target: /meals # container directory
    environment:
      FLASK_DEBUG: "true"
    ports:
      - "5001:80"  # host:container
#    expose:
#      - 80

  diet-service:
    build: ./diets
    volumes:
      - type: bind
        source: ./diets #host directory
        target: /diets # container directory
    environment:
      FLASK_DEBUG: "true"
    ports:
      - "5002:80"  # host:container
#    expose:
#      - 80

  reverse:
    build: ./reverse
    ports:
      - "80:80"
    depends_on:
      - meals-service
      - diet-service